/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.groboclown.p4plugin.ui.vcsroot;

import com.intellij.icons.AllIcons;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import net.groboclown.p4.server.api.config.part.ConfigPart;
import net.groboclown.p4plugin.ui.SwingUtil;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.lang.reflect.Method;
import java.util.ResourceBundle;

public class ConfigPartWrapper {
    private static final Icon DELETE_ITEM = AllIcons.General.Remove;
    private static final Icon MOVE_UP = AllIcons.Actions.MoveUp;
    private static final Icon MOVE_DOWN = AllIcons.Actions.MoveDown;
    private static final Icon EXPAND_DESCRIPTION = AllIcons.Actions.ShowAsTree;  // need better cross-version icon
    private static final Icon COLLAPSE_DESCRIPTION = AllIcons.General.ArrowDown;

    private final ConfigPartUI ui;
    private int position;

    private JPanel rootPane;
    private JPanel panelContainer;
    private JButton myRemoveButton;
    private JButton myUpButton;
    private JButton myDownButton;
    private JPanel myPartDescriptionPanel;
    private JTextArea myPartDescription;
    private JPanel headerPanel;
    private JButton myDescriptionToggle;
    private JLabel myPartName;


    ConfigPartWrapper(ConfigPartUI ui, ListPositionChangeController listPosController) {
        this.ui = ui;

        SwingUtil.iconOnlyButton(myRemoveButton, DELETE_ITEM, SwingUtil.ButtonType.MINOR);
        myRemoveButton.addActionListener(e -> listPosController.removePart());

        SwingUtil.iconOnlyButton(myUpButton, MOVE_UP, SwingUtil.ButtonType.MINOR);
        myUpButton.setEnabled(false);
        myUpButton.addActionListener(e -> listPosController.moveUpPosition());

        SwingUtil.iconOnlyButton(myDownButton, MOVE_DOWN, SwingUtil.ButtonType.MINOR);
        myDownButton.setEnabled(false);
        myDownButton.addActionListener(e -> listPosController.moveDownPosition());

        myPartDescriptionPanel.setVisible(false);
        myPartDescription.setText(ui.getPartDescription());

        myPartName.setText(ui.getPartTitle());

        SwingUtil.iconOnlyButton(myDescriptionToggle, EXPAND_DESCRIPTION, SwingUtil.ButtonType.ACCENT);
        myDescriptionToggle.addActionListener((e) -> {
            boolean nextVisibleStateEnabled = !myPartDescriptionPanel.isVisible();
            Icon icon = nextVisibleStateEnabled
                    ? COLLAPSE_DESCRIPTION
                    : EXPAND_DESCRIPTION;
            myPartDescriptionPanel.setVisible(nextVisibleStateEnabled);
            SwingUtil.iconOnlyButton(myDescriptionToggle, icon, SwingUtil.ButtonType.ACCENT);
            rootPane.revalidate();
            rootPane.doLayout();
        });

        panelContainer.add(ui.getPanel(), BorderLayout.CENTER);

        rootPane.doLayout();
    }


    JComponent getRootPane() {
        return rootPane;
    }

    int getPosition() {
        return position;
    }

    ConfigPart getOriginalConfigPart() {
        return ui.getPart();
    }

    @SuppressWarnings("unchecked")
    ConfigPart updateConfigPart() {
        return ui.loadUIValuesIntoPart(ui.getPart());
    }

    void setListPosition(int pos, boolean isFirst, boolean isLast) {
        this.position = pos;
        myUpButton.setEnabled(!isFirst);
        myDownButton.setEnabled(!isLast);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPane = new JPanel();
        rootPane.setLayout(new BorderLayout(0, 0));
        rootPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null,
                TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        panelContainer = new JPanel();
        panelContainer.setLayout(new BorderLayout(0, 0));
        rootPane.add(panelContainer, BorderLayout.CENTER);
        panelContainer.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(4, 4, 2, 4), null,
                TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        headerPanel = new JPanel();
        headerPanel.setLayout(new BorderLayout(0, 0));
        rootPane.add(headerPanel, BorderLayout.NORTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        headerPanel.add(panel1, BorderLayout.NORTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.EAST);
        myRemoveButton = new JButton();
        myRemoveButton.setHideActionText(true);
        myRemoveButton.setHorizontalAlignment(0);
        myRemoveButton.setHorizontalTextPosition(0);
        myRemoveButton.setText("");
        myRemoveButton.setToolTipText(
                this.$$$getMessageFromBundle$$$("net/groboclown/p4plugin/P4Bundle", "configuration.stack.remove"));
        panel2.add(myRemoveButton);
        myUpButton = new JButton();
        myUpButton.setHideActionText(true);
        myUpButton.setHorizontalAlignment(0);
        myUpButton.setHorizontalTextPosition(0);
        myUpButton.setText("");
        myUpButton.setToolTipText(
                this.$$$getMessageFromBundle$$$("net/groboclown/p4plugin/P4Bundle", "configuration.stack.move-up"));
        panel2.add(myUpButton);
        myDownButton = new JButton();
        myDownButton.setHideActionText(true);
        myDownButton.setHorizontalAlignment(0);
        myDownButton.setHorizontalTextPosition(0);
        myDownButton.setText("");
        myDownButton.setToolTipText(
                this.$$$getMessageFromBundle$$$("net/groboclown/p4plugin/P4Bundle", "configuration.stack.move-down"));
        panel2.add(myDownButton);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:grow"));
        panel1.add(panel3, BorderLayout.CENTER);
        myDescriptionToggle = new JButton();
        myDescriptionToggle.setText("");
        myDescriptionToggle.setToolTipText(this.$$$getMessageFromBundle$$$("net/groboclown/p4plugin/P4Bundle",
                "configuration.stack.wrapper.description.toggle.tooltip"));
        CellConstraints cc = new CellConstraints();
        panel3.add(myDescriptionToggle, cc.xy(1, 1));
        myPartName = new JLabel();
        myPartName.setText("Label");
        panel3.add(myPartName, cc.xy(3, 1));
        myPartDescriptionPanel = new JPanel();
        myPartDescriptionPanel.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        headerPanel.add(myPartDescriptionPanel, BorderLayout.CENTER);
        myPartDescription = new JTextArea();
        myPartDescription.setEditable(false);
        myPartDescription.setLineWrap(true);
        myPartDescription.setWrapStyleWord(true);
        myPartDescriptionPanel.add(myPartDescription, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
    }

    private static Method $$$cachedGetBundleMethod$$$ = null;

    private String $$$getMessageFromBundle$$$(String path, String key) {
        ResourceBundle bundle;
        try {
            Class<?> thisClass = this.getClass();
            if ($$$cachedGetBundleMethod$$$ == null) {
                Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
                $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
            }
            bundle = (ResourceBundle) $$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
        } catch (Exception e) {
            bundle = ResourceBundle.getBundle(path);
        }
        return bundle.getString(key);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPane;
    }

}
