/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.groboclown.p4plugin.ui.vcsroot;

import com.intellij.icons.AllIcons;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import net.groboclown.p4.server.api.config.part.ConfigPart;

import javax.swing.*;
import java.awt.*;
import java.util.ResourceBundle;

public class ConfigPartWrapper {
    private final ConfigPartUI ui;
    private int position;

    private JPanel rootPane;
    private JPanel panelContainer;
    private JButton myRemoveButton;
    private JButton myUpButton;
    private JButton myDownButton;
    private JPanel myPartDescriptionPanel;
    private JCheckBox myPartNameToggle;
    private JTextArea myPartDescription;
    private JPanel headerPanel;


    ConfigPartWrapper(ConfigPartUI ui, ListPositionChangeController listPosController) {
        this.ui = ui;
        ListPositionChangeController listPosController1 = listPosController;

        myRemoveButton.addActionListener(e -> listPosController.removePart());
        myRemoveButton.setIcon(AllIcons.Actions.Delete);
        myRemoveButton.setPreferredSize(new Dimension(
                AllIcons.Actions.Delete.getIconWidth() + 2,
                AllIcons.Actions.Delete.getIconHeight() + 2)
        );

        myUpButton.setEnabled(false);
        myUpButton.addActionListener(e -> listPosController.moveUpPosition());
        myUpButton.setIcon(AllIcons.Actions.MoveUp);
        myUpButton.setPreferredSize(new Dimension(
                AllIcons.Actions.MoveUp.getIconWidth() + 2,
                AllIcons.Actions.MoveUp.getIconHeight() + 2)
        );

        myDownButton.setEnabled(false);
        myDownButton.addActionListener(e -> listPosController.moveDownPosition());
        myDownButton.setIcon(AllIcons.Actions.MoveDown);
        myDownButton.setPreferredSize(new Dimension(
                AllIcons.Actions.MoveDown.getIconWidth() + 2,
                AllIcons.Actions.MoveDown.getIconHeight() + 2)
        );

        myPartDescriptionPanel.setVisible(false);
        myPartDescription.setText(ui.getPartDescription());

        myPartNameToggle.setText(ui.getPartTitle());
        myPartNameToggle.setPressedIcon(AllIcons.Nodes.TreeClosed);
        myPartNameToggle.setRolloverIcon(AllIcons.Nodes.TreeClosed);
        myPartNameToggle.setIcon(AllIcons.Nodes.TreeClosed);
        myPartNameToggle.setSelectedIcon(AllIcons.Nodes.TreeExpandNode);
        myPartNameToggle.setRolloverSelectedIcon(AllIcons.Nodes.TreeExpandNode);
        myPartNameToggle.addActionListener((e) -> {
            myPartDescriptionPanel.setVisible(myPartNameToggle.isSelected());
            headerPanel.doLayout();
        });

        panelContainer.add(ui.getPanel(), BorderLayout.CENTER);

        rootPane.doLayout();
    }


    JComponent getRootPane() {
        return rootPane;
    }

    int getPosition() {
        return position;
    }

    ConfigPart getConfigPart() {
        return ui.getPart();
    }


    void setListPosition(int pos, boolean isFirst, boolean isLast) {
        this.position = pos;
        myUpButton.setEnabled(!isFirst);
        myDownButton.setEnabled(!isLast);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPane = new JPanel();
        rootPane.setLayout(new BorderLayout(0, 0));
        rootPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        panelContainer = new JPanel();
        panelContainer.setLayout(new BorderLayout(0, 0));
        rootPane.add(panelContainer, BorderLayout.CENTER);
        panelContainer.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(4, 4, 2, 4), null));
        headerPanel = new JPanel();
        headerPanel.setLayout(new BorderLayout(0, 0));
        rootPane.add(headerPanel, BorderLayout.NORTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        headerPanel.add(panel1, BorderLayout.NORTH);
        myPartNameToggle = new JCheckBox();
        myPartNameToggle.setText("<component name>");
        panel1.add(myPartNameToggle, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.EAST);
        myRemoveButton = new JButton();
        myRemoveButton.setHideActionText(true);
        myRemoveButton.setHorizontalAlignment(0);
        myRemoveButton.setHorizontalTextPosition(0);
        myRemoveButton.setText("");
        myRemoveButton.setToolTipText(
                ResourceBundle.getBundle("net/groboclown/p4plugin/P4Bundle").getString("configuration.stack.remove"));
        panel2.add(myRemoveButton);
        myUpButton = new JButton();
        myUpButton.setHideActionText(true);
        myUpButton.setHorizontalAlignment(0);
        myUpButton.setHorizontalTextPosition(0);
        myUpButton.setText("");
        myUpButton.setToolTipText(
                ResourceBundle.getBundle("net/groboclown/p4plugin/P4Bundle").getString("configuration.stack.move-up"));
        panel2.add(myUpButton);
        myDownButton = new JButton();
        myDownButton.setHideActionText(true);
        myDownButton.setHorizontalAlignment(0);
        myDownButton.setHorizontalTextPosition(0);
        myDownButton.setText("");
        myDownButton.setToolTipText(ResourceBundle.getBundle("net/groboclown/p4plugin/P4Bundle")
                .getString("configuration.stack.move-down"));
        panel2.add(myDownButton);
        myPartDescriptionPanel = new JPanel();
        myPartDescriptionPanel.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        headerPanel.add(myPartDescriptionPanel, BorderLayout.CENTER);
        myPartDescription = new JTextArea();
        myPartDescription.setEditable(false);
        myPartDescription.setLineWrap(true);
        myPartDescription.setWrapStyleWord(true);
        CellConstraints cc = new CellConstraints();
        myPartDescriptionPanel.add(myPartDescription, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPane;
    }
}
