/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.groboclown.idea.p4ic.ui.config;

import com.intellij.openapi.project.Project;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import net.groboclown.idea.p4ic.config.P4ProjectConfigComponent;
import net.groboclown.idea.p4ic.ui.config.props.ConfigStackPanel;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import java.awt.*;

public class P4Config2Panel {
    private ConfigStackPanel configStackPanel;
    private ResolvedPropertiesPanel resolvePropertiesPanel;
    private JPanel rootPanel;
    private JSplitPane splitPane;

    public P4Config2Panel() {
        $$$setupUI$$$();
        configStackPanel.addChangeListener(resolvePropertiesPanel.getConfigurationUpdatedListener());
        splitPane.setDividerLocation(0.6);
    }

    private void createUIComponents() {
        // place custom component creation code here
        configStackPanel = new ConfigStackPanel();
    }

    void initialize(@Nullable Project project) {
        configStackPanel.initialize(project);
    }

    public void saveSettingsToConfig(@NotNull P4ProjectConfigComponent configComponent) {
        configStackPanel.loadFromUI(configComponent);
    }

    public void loadSettingsIntoGUI(@NotNull P4ProjectConfigComponent configComponent) {
        configStackPanel.updateUI(configComponent);
    }

    public boolean isModified(@NotNull P4ProjectConfigComponent configComponent) {
        return configStackPanel.isModified(configComponent);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        splitPane = new JSplitPane();
        splitPane.setDividerLocation(180);
        splitPane.setOrientation(0);
        CellConstraints cc = new CellConstraints();
        rootPanel.add(splitPane, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        resolvePropertiesPanel = new ResolvedPropertiesPanel();
        splitPane.setRightComponent(resolvePropertiesPanel.$$$getRootComponent$$$());
        splitPane.setLeftComponent(configStackPanel.$$$getRootComponent$$$());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
