/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.groboclown.idea.p4ic.ui.config;

import com.intellij.openapi.project.Project;
import net.groboclown.idea.p4ic.config.ManualP4Config;
import net.groboclown.idea.p4ic.config.UserProjectPreferences;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;
import java.util.ResourceBundle;

public class P4SettingsPanel {
    private P4ConfigPanel myP4ConfigPanel;
    private UserPreferencesPanel myUserPreferencesPanel;
    private JPanel myRootPanel;

    boolean isModified(@NotNull final ManualP4Config myConfig, @NotNull final UserProjectPreferences preferences) {
        return myP4ConfigPanel.isModified(myConfig) || myUserPreferencesPanel.isModified(preferences);
    }

    void saveSettingsToConfig(@NotNull final ManualP4Config config, @NotNull final UserProjectPreferences preferences) {
        myP4ConfigPanel.saveSettingsToConfig(config);
        myUserPreferencesPanel.saveSettingsToConfig(preferences);
    }

    void loadSettingsIntoGUI(@NotNull final ManualP4Config config, @NotNull final UserProjectPreferences preferences) {
        myP4ConfigPanel.loadSettingsIntoGUI(config);
        myUserPreferencesPanel.loadSettingsIntoGUI(preferences);
    }

    JPanel getPanel() {
        return myRootPanel;
    }

    void initialize(final Project project) {
        myP4ConfigPanel.initialize(project);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        myRootPanel = new JPanel();
        myRootPanel.setLayout(new BorderLayout(0, 0));
        final JTabbedPane tabbedPane1 = new JTabbedPane();
        myRootPanel.add(tabbedPane1, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab(ResourceBundle.getBundle("net/groboclown/idea/p4ic/P4Bundle")
                .getString("user.settings.connection"), panel1);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, BorderLayout.CENTER);
        myP4ConfigPanel = new P4ConfigPanel();
        scrollPane1.setViewportView(myP4ConfigPanel.$$$getRootComponent$$$());
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        tabbedPane1
                .addTab(ResourceBundle.getBundle("net/groboclown/idea/p4ic/P4Bundle").getString("user.settings.prefs"),
                        panel2);
        final JScrollPane scrollPane2 = new JScrollPane();
        panel2.add(scrollPane2, BorderLayout.CENTER);
        myUserPreferencesPanel = new UserPreferencesPanel();
        scrollPane2.setViewportView(myUserPreferencesPanel.$$$getRootComponent$$$());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return myRootPanel;
    }
}
