/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.groboclown.idea.p4ic.ui.config.props;

import com.intellij.icons.AllIcons;
import com.intellij.openapi.Disposable;
import com.intellij.openapi.application.ApplicationManager;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.popup.JBPopupFactory;
import com.intellij.openapi.ui.popup.ListPopup;
import com.intellij.openapi.ui.popup.PopupStep;
import com.intellij.openapi.ui.popup.util.BaseListPopupStep;
import com.intellij.openapi.util.Disposer;
import com.intellij.util.Consumer;
import com.intellij.util.ui.EmptyIcon;
import net.groboclown.idea.p4ic.P4Bundle;
import net.groboclown.idea.p4ic.background.BackgroundAwtActionRunner;
import net.groboclown.idea.p4ic.config.P4ProjectConfig;
import net.groboclown.idea.p4ic.config.P4ProjectConfigComponent;
import net.groboclown.idea.p4ic.config.P4ProjectConfigStack;
import net.groboclown.idea.p4ic.config.part.ClientNameDataPart;
import net.groboclown.idea.p4ic.config.part.ConfigPart;
import net.groboclown.idea.p4ic.config.part.DataPart;
import net.groboclown.idea.p4ic.config.part.EnvCompositePart;
import net.groboclown.idea.p4ic.config.part.FileDataPart;
import net.groboclown.idea.p4ic.config.part.RelativeConfigCompositePart;
import net.groboclown.idea.p4ic.config.part.RequirePasswordDataPart;
import net.groboclown.idea.p4ic.config.part.ServerFingerprintDataPart;
import net.groboclown.idea.p4ic.config.part.SimpleDataPart;
import net.groboclown.idea.p4ic.ui.ComponentListPanel;
import net.groboclown.idea.p4ic.ui.config.RequestConfigurationLoadListener;
import org.jetbrains.annotations.NonNls;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.ResourceBundle;

public class ConfigStackPanel
        implements RequestConfigurationLoadListener, Disposable {
    private static final Logger LOG = Logger.getInstance(ConfigStackPanel.class);

    private Project project;
    private JPanel rootPanel;
    private JButton addEntryButton;
    private ComponentListPanel<ConfigPartPanel<?>> componentList;
    private P4ProjectConfig tempConfig;

    private final ArrayList<ConfigurationUpdatedListener> changeListeners =
            new ArrayList<ConfigurationUpdatedListener>(2);

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setHorizontalScrollBarPolicy(31);
        rootPanel.add(scrollPane1, BorderLayout.CENTER);
        scrollPane1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4), null));
        scrollPane1.setViewportView(componentList);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        rootPanel.add(panel1, BorderLayout.NORTH);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(4, 4, 4, 4), null));
        final JLabel label1 = new JLabel();
        Font label1Font = UIManager.getFont("TitledBorder.font");
        if (label1Font != null) {
            label1.setFont(label1Font);
        }
        this.$$$loadLabelText$$$(label1,
                ResourceBundle.getBundle("net/groboclown/idea/p4ic/P4Bundle").getString("configuration.stack.title"));
        panel1.add(label1, BorderLayout.WEST);
        addEntryButton = new JButton();
        addEntryButton.setText("");
        addEntryButton.setToolTipText(
                ResourceBundle.getBundle("net/groboclown/idea/p4ic/P4Bundle").getString("configuration.stack.add"));
        panel1.add(addEntryButton, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadLabelText$$$(JLabel component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) {
                    break;
                }
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setDisplayedMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    enum ConfigPartType {
        ENVIRONMENT(
                EnvCompositePart.class,
                P4Bundle.getString("configuration.stack.type.env"),
                AllIcons.Ide.Link) {
            @NotNull
            @Override
            ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part) {
                // For Env, we don't have any settings to copy.  So always use a new one.
                return new EnvConfigPartPanel(project, new EnvCompositePart(project));
            }
        },
        PROPERTY(
                SimpleDataPart.class,
                P4Bundle.getString("configuration.stack.type.property"),
                EmptyIcon.ICON_16) {
            @NotNull
            @Override
            ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part) {
                final SimpleDataPart cp;
                if (part == null) {
                    cp = new SimpleDataPart(project, (Map<String, String>) null);
                } else {
                    cp = new SimpleDataPart(project, (DataPart) part);
                }
                return new PropertyConfigPanel(project, cp);
            }
        },
        CLIENT_NAME(
                ClientNameDataPart.class,
                P4Bundle.getString("configuration.stack.type.client-name"),
                EmptyIcon.ICON_16) {
            @NotNull
            @Override
            ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part) {
                final ClientNameDataPart cp = new ClientNameDataPart();
                if (part != null) {
                    cp.setClientname(((DataPart) part).getClientname());
                }
                return new ClientNameConfigPartPanel(project, cp);
            }
        },
        FILE(
                FileDataPart.class,
                P4Bundle.getString("configuration.stack.type.file"),
                EmptyIcon.ICON_16) {
            @NotNull
            @Override
            ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part) {
                final FileDataPart cp = new FileDataPart(project);
                if (part != null) {
                    cp.setConfigFile(((FileDataPart) part).getConfigFile());
                }
                return new FileConfigPartPanel(project, cp);
            }
        },
        RELATIVE_FILE(
                RelativeConfigCompositePart.class,
                P4Bundle.getString("configuration.stack.type.relative-file"),
                EmptyIcon.ICON_16) {
            @NotNull
            @Override
            ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part) {
                final RelativeConfigCompositePart cp = new RelativeConfigCompositePart(project);
                if (part != null) {
                    cp.setName(((RelativeConfigCompositePart) part).getName());
                }
                return new RelativeConfigPartPanel(project, cp);
            }
        },
        REQUIRE_PASSWORD(
                RequirePasswordDataPart.class,
                P4Bundle.getString("configuration.stack.type.require-password"),
                EmptyIcon.ICON_16) {
            @NotNull
            @Override
            ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part) {
                // Require password has no settings, so always use a new part.
                return new RequirePasswordConfigPartPanel(project, new RequirePasswordDataPart());
            }
        },
        SERVER_FINGERPRINT(
                ServerFingerprintDataPart.class,
                P4Bundle.getString("configuration.stack.type.server-fingerprint"),
                EmptyIcon.ICON_16) {
            @NotNull
            @Override
            ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part) {
                final ServerFingerprintDataPart cp = new ServerFingerprintDataPart();
                if (part != null) {
                    cp.setServerFingerprint(((ServerFingerprintDataPart) part).getServerFingerprint());
                }
                return new ServerFingerprintConfigPartPanel(project, cp);
            }
        };

        private final Class<? extends ConfigPart> partClass;
        private final String title;
        private final Icon icon;

        ConfigPartType(@NotNull Class<? extends ConfigPart> partClass, @NotNull @NonNls String title,
                @NotNull Icon icon) {
            this.partClass = partClass;
            this.title = title;
            this.icon = icon;
        }

        /**
         * Create a new panel for the given part as a template.  The given part must be copied
         * into the panel, and not directly manipulated by the panel.
         *
         * @param project project
         * @param part    source part
         * @return panel
         */
        @NotNull
        abstract ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part);
    }

    public ConfigStackPanel() {
        $$$setupUI$$$();
        addEntryButton.setIcon(AllIcons.General.Add);
        addEntryButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                chooseEntry();
            }
        });


        componentList.addChildListChangeListener(new ComponentListPanel.ChildListChanged<ConfigPartPanel<?>>() {
            @Override
            public void onChildListChanged(Collection<ConfigPartPanel<?>> childList) {
                sendConfigStackUpdated();
            }
        });
    }

    public void initialize(@Nullable Project project) {
        this.project = project;
    }

    public void addConfigurationUpdatedListener(@NotNull ConfigurationUpdatedListener changeListener) {
        changeListeners.add(changeListener);
    }

    public void updateUI(@NotNull final P4ProjectConfigComponent component) {
        // Need to get the user parts, and add them in reverse order.
        // This is because the logic around "addConfigPart" always sticks the
        // newly added part to the top of the list.
        final ArrayList<ConfigPart> parts = new ArrayList<ConfigPart>(component.getUserConfigParts());
        Collections.reverse(parts);

        if (ApplicationManager.getApplication().isDispatchThread()) {
            componentList.removeAllChildren();

            for (ConfigPart part : parts) {
                addConfigPart(part);
            }
        } else {
            ApplicationManager.getApplication().invokeLater(new Runnable() {
                @Override
                public void run() {
                    componentList.removeAllChildren();

                    for (ConfigPart part : parts) {
                        addConfigPart(part);
                    }
                }
            });
        }
    }

    public void loadFromUI(@NotNull final P4ProjectConfigComponent component) {
        updateConfigPartFromUI();
        final List<ConfigPartPanel<?>> partPanels = componentList.getChildren();
        ArrayList<ConfigPart> parts = new ArrayList<ConfigPart>(partPanels.size());
        for (ConfigPartPanel<?> cmp : partPanels) {
            cmp.updateConfigPartFromUI();
            parts.add(cmp.copyPart());
        }
        component.setUserConfigParts(parts);
    }

    public boolean isModified(@NotNull P4ProjectConfigComponent configComponent) {
        final List<ConfigPart> originalParts = configComponent.getUserConfigParts();
        final List<ConfigPartPanel<?>> partPanels = componentList.getChildren();
        if (originalParts.size() != partPanels.size()) {
            return true;
        }
        final Iterator<ConfigPart> origs = originalParts.iterator();
        final Iterator<ConfigPartPanel<?>> nows = partPanels.iterator();
        while (origs.hasNext() && nows.hasNext()) {
            ConfigPart orig = origs.next();
            ConfigPartPanel<?> now = nows.next();
            if (isModified(now, orig)) {
                return true;
            }
        }
        return false;
    }

    private <T extends ConfigPart> boolean isModified(@NotNull ConfigPartPanel<T> panel, @NotNull ConfigPart part) {
        T casted = panel.castAs(part);
        return casted == null || panel.isModified(casted);
    }


    @Override
    public void dispose() {
        this.componentList.removeAllChildren();
        if (tempConfig != null) {
            Disposer.dispose(tempConfig);
        }
        this.project = null;
        this.tempConfig = null;
    }

    @NotNull
    @Override
    public P4ProjectConfig updateConfigPartFromUI() {
        final List<ConfigPartPanel<?>> partPanels = componentList.getChildren();
        ArrayList<ConfigPart> parts = new ArrayList<ConfigPart>(partPanels.size());
        for (ConfigPartPanel<?> configPartPanel : componentList.getChildren()) {
            configPartPanel.updateConfigPartFromUI();
            configPartPanel.getConfigPart().reload();
            parts.add(configPartPanel.copyPart());
        }
        if (LOG.isDebugEnabled()) {
            LOG.debug("Creating project config with " + parts);
        }
        P4ProjectConfigStack ret = new P4ProjectConfigStack(project, parts);
        ret.refresh();
        return ret;
    }

    /**
     * Called as part of the initialization from a project config.  The listener must be invoked
     * after all these are created.
     *
     * @param part part to add
     */
    private void addConfigPart(@NotNull ConfigPart part) {
        final Class<? extends ConfigPart> partClass = part.getClass();
        for (ConfigPartType configPartType : ConfigPartType.values()) {
            if (configPartType.partClass.equals(partClass)) {
                addConfigPartPanel(configPartType.createPanel(project, part));
                return;
            }
        }
        throw new IllegalArgumentException("Unexpected config part " + part);
    }

    private void addConfigPartType(@NotNull ConfigPartType type) {
        addConfigPartPanel(type.createPanel(project, null));
    }

    private <T extends ConfigPart> void addConfigPartPanel(@NotNull final ConfigPartPanel<T> panel) {
        // panel.getRootPanel().setMaximumSize(new Dimension(-1, panel.getRootPanel().getMinimumSize().height));
        panel.setRequestConfigurationLoadListener(this);
        componentList.addChildAt(0, panel);
        ApplicationManager.getApplication().executeOnPooledThread(new Runnable() {
            @Override
            public void run() {
                panel.getConfigPart().reload();
                sendConfigStackUpdated();
            }
        });
    }

    private void sendConfigStackUpdated() {
        // The refresh can take a long time, so run it in the background.
        if (! Disposer.isDisposed(this)) {
            BackgroundAwtActionRunner
                    .runBackgrounAwtAction(new BackgroundAwtActionRunner.BackgroundAwtAction<P4ProjectConfig>() {
                        @Override
                        public P4ProjectConfig runBackgroundProcess() {
                            final List<ConfigPartPanel<?>> partComponents = componentList.getChildren();
                            ArrayList<ConfigPart> parts = new ArrayList<ConfigPart>(partComponents.size());
                            for (ConfigPartPanel<?> configPartPanel : partComponents) {
                                parts.add(configPartPanel.getConfigPart());
                            }

                            if (tempConfig != null) {
                                Disposer.dispose(tempConfig);
                                tempConfig = null;
                            }
                            final P4ProjectConfig config;
                            if (project == null) {
                                config = null;
                            } else {
                                config = new P4ProjectConfigStack(project, parts);
                                config.refresh();
                            }
                            return config;
                        }

                        @Override
                        public void runAwtProcess(final @Nullable P4ProjectConfig config) {
                            // Yes, this performs extra work that shouldn't be in the AWT;
                            // however, because of the slowness of the background process, we
                            // want to wait on performing dispose checks until the last possible
                            // moment.
                            if (config != null) {
                                if (Disposer.isDisposed(ConfigStackPanel.this)) {
                                    Disposer.dispose(config);
                                } else {
                                    Disposer.register(ConfigStackPanel.this, config);
                                    for (ConfigurationUpdatedListener changeListener : changeListeners) {
                                        changeListener.onConfigurationUpdated(config);
                                    }
                                    tempConfig = config;
                                }
                            }
                        }
                    });
        }
    }


    // CalledInAWT
    private void chooseEntry() {
        final ListPopup popup = createConfigPartPopup(new Consumer<ConfigPartType>() {
            @Override
            public void consume(ConfigPartType configPartType) {
                if (configPartType != null) {
                    addConfigPartType(configPartType);
                }
            }
        });
        popup.showUnderneathOf(addEntryButton);

    }


    private ListPopup createConfigPartPopup(final Consumer<ConfigPartType> onChosen) {
        return JBPopupFactory.getInstance().createListPopup(new BaseListPopupStep<ConfigPartType>(
                P4Bundle.getString("configuration.stack.choose.title"),
                ConfigPartType.values()) {
            @Nullable
            @Override
            public PopupStep onChosen(ConfigPartType configPartType, boolean finalChoice) {
                onChosen.consume(configPartType);
                return super.onChosen(configPartType, finalChoice);
            }

            @Override
            public void canceled() {
                onChosen.consume(null);
            }

            @Nullable
            @Override
            public Icon getIconFor(ConfigPartType configPartType) {
                return configPartType.icon;
            }

            @NotNull
            @Override
            public String getTextFor(ConfigPartType configPartType) {
                return configPartType.title;
            }
        });
    }


    private void createUIComponents() {
        // place custom component creation code here
        componentList = new ComponentListPanel<ConfigPartPanel<?>>();
    }
}
