/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.groboclown.idea.p4ic.ui.config.props;

import com.intellij.icons.AllIcons;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.DialogWrapper;
import com.intellij.openapi.util.SystemInfo;
import com.intellij.ui.components.JBList;
import com.intellij.ui.components.JBScrollPane;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.intellij.util.ui.UIUtil;
import com.jgoodies.common.collect.ArrayListModel;
import net.groboclown.idea.p4ic.P4Bundle;
import net.groboclown.idea.p4ic.config.P4ProjectConfig;
import net.groboclown.idea.p4ic.config.P4ProjectConfigStack;
import net.groboclown.idea.p4ic.config.part.*;
import net.groboclown.idea.p4ic.ui.util.BackgroundAwtActionRunner;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.concurrent.atomic.AtomicLong;

public class ConfigStackPanel {
    private static AtomicLong nextConfigPanelId = new AtomicLong(0);

    private Project project;
    private JPanel rootPanel;
    private JList configList;
    private JButton addEntryButton;
    private JButton removeEntryButton;
    private JButton moveEntryUpButton;
    private JButton moveEntryDownButton;

    private final Map<String, ConfigPartPanel<?>> configPanelIdMap = new HashMap<String, ConfigPartPanel<?>>();

    private ArrayListModel/*<ConfigPartPanel>*/ componentStack = new ArrayListModel/*<ConfigPartPanel>*/();

    private final ArrayList<ConfigurationUpdatedListener> changeListeners =
            new ArrayList<ConfigurationUpdatedListener>(2);
    private final ConfigurationUpdatedListener proxyConfigurationUpdatedListener = new ConfigurationUpdatedListener() {
        @Override
        public void onConfigurationUpdated(@NotNull P4ProjectConfig evt) {
            for (ConfigurationUpdatedListener changeListener : changeListeners) {
                changeListener.onConfigurationUpdated(evt);
            }
        }
    };
    private final ConfigPartUpdatedListener configPartUpdatedListener = new ConfigPartUpdatedListener() {
        @Override
        public void onConfigPartUpdated() {
            sendConfigStackUpdated();
        }
    };

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        final JScrollPane scrollPane1 = new JScrollPane();
        rootPanel.add(scrollPane1, BorderLayout.CENTER);
        configList = new JList();
        configList.setSelectionMode(0);
        scrollPane1.setViewportView(configList);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(panel1, BorderLayout.EAST);
        addEntryButton = new JButton();
        addEntryButton.setText("");
        addEntryButton.setToolTipText(
                ResourceBundle.getBundle("net/groboclown/idea/p4ic/P4Bundle").getString("configuration.stack.add"));
        panel1.add(addEntryButton,
                new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        removeEntryButton = new JButton();
        removeEntryButton.setText("");
        removeEntryButton.setToolTipText(
                ResourceBundle.getBundle("net/groboclown/idea/p4ic/P4Bundle").getString("configuration.stack.remove"));
        panel1.add(removeEntryButton,
                new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1,
                new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1,
                        GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        moveEntryUpButton = new JButton();
        moveEntryUpButton.setText("");
        moveEntryUpButton.setToolTipText(
                ResourceBundle.getBundle("net/groboclown/idea/p4ic/P4Bundle").getString("configuration.stack.move-up"));
        panel1.add(moveEntryUpButton,
                new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        moveEntryDownButton = new JButton();
        moveEntryDownButton.setText("");
        moveEntryDownButton.setToolTipText(ResourceBundle.getBundle("net/groboclown/idea/p4ic/P4Bundle")
                .getString("configuration.stack.move-down"));
        panel1.add(moveEntryDownButton,
                new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
                        GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

    enum ConfigPartType {
        // TODO make these icons all nice.
        ENVIRONMENT(EnvCompositePart.class, "configuration.stack.type.env", AllIcons.Ide.Link) {
            @NotNull
            @Override
            ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part) {
                if (part == null) {
                    part = new EnvCompositePart(project);
                }
                return new EnvConfigPartPanel(project, getNextConfigPanelId(), (EnvCompositePart) part);
            }
        },
        PROPERTY(SimpleDataPart.class, "configuration.stack.type.property", AllIcons.General.Configure) {
            @NotNull
            @Override
            ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part) {
                if (part == null) {
                    part = new SimpleDataPart(project, null);
                }
                // FIXME
                return null;
            }
        },
        FILE(FileDataPart.class, "configuration.stack.type.file", AllIcons.FileTypes.Properties) {
            @NotNull
            @Override
            ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part) {
                if (part == null) {
                    part = new FileDataPart(project);
                }
                // FIXME
                return null;
            }
        },
        RELATIVE_FILE(RelativeConfigCompositePart.class, "configuration.stack.type.relative-file",
                AllIcons.FileTypes.Text) {
            @NotNull
            @Override
            ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part) {
                if (part == null) {
                    part = new RelativeConfigCompositePart(project);
                }
                // FIXME
                return null;
            }
        },
        REQUIRE_PASSWORD(RequirePasswordDataPart.class, "configuration.stack.type.require-password",
                AllIcons.General.PasswordLock) {
            @NotNull
            @Override
            ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part) {
                if (part == null) {
                    part = new RequirePasswordDataPart();
                }
                return new RequirePasswordConfigPartPanel(project, getNextConfigPanelId(),
                        (RequirePasswordDataPart) part);
            }
        };

        private final Class<? extends ConfigPart> partClass;
        private final String title;
        private final Icon icon;

        ConfigPartType(@NotNull Class<? extends ConfigPart> partClass, @NotNull @Nls String title, Icon icon) {
            this.partClass = partClass;
            this.title = title;
            this.icon = icon;
        }

        @NotNull
        abstract ConfigPartPanel createPanel(@NotNull Project project, @Nullable ConfigPart part);
    }

    ConfigStackPanel(@Nullable Project project) {
        this.project = project;
        addEntryButton.setIcon(AllIcons.Actions.Cross);
        addEntryButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                chooseEntry();
            }
        });

        removeEntryButton.setIcon(AllIcons.Actions.Delete);
        removeEntryButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                removeConfigPartAt(configList.getSelectedIndex());
            }
        });

        moveEntryUpButton.setIcon(AllIcons.Actions.MoveUp);
        moveEntryUpButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                moveEntryUp(configList.getSelectedIndex());
            }
        });

        moveEntryDownButton.setIcon(AllIcons.Actions.MoveDown);
        moveEntryDownButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                moveEntryDown(configList.getSelectedIndex());
            }
        });


        configList.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                onListSelectionChanged();
            }
        });
        configList.setCellRenderer(new ConfigPartPanelCellRenderer());
    }

    public void addChangeListener(@NotNull ConfigurationUpdatedListener changeListener) {
        changeListeners.add(changeListener);
    }

    /**
     * Called as part of the initialization from a project config.  The listener must be invoked
     * after all these are created.
     *
     * @param part part to add
     */
    private void addConfigPart(@NotNull ConfigPart part) {
        final Class<? extends ConfigPart> partClass = part.getClass();
        for (ConfigPartType configPartType : ConfigPartType.values()) {
            if (configPartType.partClass.equals(partClass)) {
                addConfigPartPanel(configPartType.createPanel(project, part), false);
                return;
            }
        }
        throw new IllegalArgumentException("Unexpected config part " + part);
    }

    private void addConfigPartType(@NotNull ConfigPartType type) {
        addConfigPartPanel(type.createPanel(project, null), true);
        sendConfigStackUpdated();
    }

    private <T extends ConfigPart> void addConfigPartPanel(@NotNull ConfigPartPanel<T> panel, boolean sendUpdate) {
        panel.setConfigPartUpdatedListener(configPartUpdatedListener);
        configPanelIdMap.put(panel.getId(), panel);
        final int index = configList == null ? 0 : configList.getSelectedIndex();
        componentStack.add(index < 0 ? 0 : index, panel);
        if (sendUpdate) {
            sendConfigStackUpdated();
        }
    }

    // CalledInAWT
    private void removeConfigPartAt(int selectedIndex) {
        if (selectedIndex >= 0 && selectedIndex < componentStack.getSize()) {
            if (selectedIndex + 1 >= componentStack.getSize()) {
                configList.setSelectedIndex(0);
            }
            componentStack.remove(selectedIndex);
            sendConfigStackUpdated();
        }
    }

    private void moveEntryUp(int selectedIndex) {
        // Note: checking for > 0
        if (selectedIndex > 0 && selectedIndex < componentStack.getSize()) {
            /* ConfigPartPanel */
            Object selectedObject = componentStack.get(selectedIndex);
            componentStack.set(selectedIndex, componentStack.get(selectedIndex - 1));
            componentStack.set(selectedIndex - 1, selectedObject);
            configList.setSelectedIndex(selectedIndex - 1);
            sendConfigStackUpdated();
        }
    }

    private void moveEntryDown(int selectedIndex) {
        // Note: checking for -1 <
        if (selectedIndex >= 0 && selectedIndex - 1 < componentStack.getSize()) {
            /* ConfigPartPanel */
            Object selectedObject = componentStack.get(selectedIndex);
            componentStack.set(selectedIndex, componentStack.get(selectedIndex + 1));
            componentStack.set(selectedIndex + 1, selectedObject);
            configList.setSelectedIndex(selectedIndex + 1);
            sendConfigStackUpdated();
        }
    }

    private void onListSelectionChanged() {
        final int selectedIndex = configList.getSelectedIndex();
        if (selectedIndex < 0) {
            removeEntryButton.setEnabled(false);
            moveEntryUpButton.setEnabled(false);
            moveEntryDownButton.setEnabled(false);
        } else if (selectedIndex == 0) {
            removeEntryButton.setEnabled(true);
            moveEntryUpButton.setEnabled(false);
            moveEntryDownButton.setEnabled(true);
        } else if (selectedIndex + 1 < componentStack.size()) {
            removeEntryButton.setEnabled(true);
            moveEntryUpButton.setEnabled(true);
            moveEntryDownButton.setEnabled(true);
        } else {
            removeEntryButton.setEnabled(true);
            moveEntryUpButton.setEnabled(true);
            moveEntryDownButton.setEnabled(false);
        }
    }

    private void sendConfigStackUpdated() {
        onListSelectionChanged();
        ArrayList<ConfigPart> parts = new ArrayList<ConfigPart>(componentStack.getSize());
        for (Object o : componentStack) {
            parts.add((ConfigPart) o);
        }

        P4ProjectConfig config = new P4ProjectConfigStack(project, parts);
        proxyConfigurationUpdatedListener.onConfigurationUpdated(config);
    }

    // CalledInAWT
    private void chooseEntry() {
        BackgroundAwtActionRunner.runBackgrounAwtAction(new BackgroundAwtActionRunner
                .BackgroundAwtAction<ConfigPartType>() {
            @Override
            public ConfigPartType runBackgroundProcess() {
                ChooseConfigPartDialog dialog = new ChooseConfigPartDialog(project);
                dialog.show();
                return dialog.getChoice();
            }

            @Override
            public void runAwtProcess(ConfigPartType choice) {
                if (choice != null) {
                    addConfigPartType(choice);
                }
            }
        });
    }


    private static String getNextConfigPanelId() {
        return Long.toHexString(nextConfigPanelId.incrementAndGet());
    }


    private static class ChooseConfigPartDialog
            extends DialogWrapper {
        private JList/*<ConfigPartType>*/ list;

        private ChooseConfigPartDialog(@Nullable Project project) {
            super(project, false, IdeModalityType.MODELESS);
            setTitle(P4Bundle.getString("configuration.stack.choose.title"));
            if (!SystemInfo.isMac) {
                setButtonsAlignment(0);
            }
            list = new JBList(ConfigPartType.values());
        }

        ConfigPartType getChoice() {
            return (ConfigPartType) list.getSelectedValue();
        }

        @Nullable
        @Override
        protected JComponent createNorthPanel() {
            JPanel panel = new JPanel(new BorderLayout());
            panel.add(new JLabel(P4Bundle.getString("configuration.stack.choose")), BorderLayout.NORTH);
            return panel;
        }

        @Nullable
        @Override
        protected JComponent createCenterPanel() {
            list = new JBList(ConfigPartType.values());
            list.setCellRenderer(new ConfigPartTypeCellRenderer());
            list.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            return new JBScrollPane(list);
        }
    }

    private static class ConfigPartTypeCellRenderer
            implements ListCellRenderer/*<ConfigPartType>*/ {
        final JLabel label = new JLabel();

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            ConfigPartType type = (ConfigPartType) value;
            label.setFont(UIUtil.getListFont());
            label.setText(P4Bundle.getString(type.title));
            label.setIcon(type.icon);
            if (isSelected) {
                label.setBackground(UIUtil.getListSelectionBackground());
                label.setForeground(UIUtil.getListSelectionForeground());
            } else {
                label.setBackground(UIUtil.getListBackground());
                label.setForeground(UIUtil.getListForeground());
            }
            return label;
        }
    }

    private static class ConfigPartPanelCellRenderer
            implements ListCellRenderer/*<ConfigPartPanel>*/ {
        final JPanel panel = new JPanel();

        ConfigPartPanelCellRenderer() {
            panel.setLayout(new BorderLayout());
        }

        @Override
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
            ConfigPartPanel part = (ConfigPartPanel) value;
            JPanel component = part.getRootPanel();
            panel.removeAll();
            panel.add(component, BorderLayout.CENTER);
            panel.setBorder(BorderFactory.createLineBorder(UIUtil.getBoundsColor(isSelected)));
            panel.validate();
            return panel;
        }
    }

    private void createUIComponents() {
        // place custom component creation code here
    }
}
