/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.groboclown.idea.p4ic.ui.config.props;

import com.intellij.openapi.project.Project;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.util.ui.UIUtil;
import net.groboclown.idea.p4ic.config.part.EnvCompositePart;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.awt.*;
import java.util.ResourceBundle;

public class EnvConfigPartPanel
        extends ConfigPartPanel<EnvCompositePart> {
    private JPanel rootPanel;
    private JLabel titleLabel;
    private JTextPane descriptionLabel;

    EnvConfigPartPanel(@NotNull Project project, @NotNull String id, @NotNull EnvCompositePart part) {
        super(project, id, part);
    }

    @Override
    @NotNull
    EnvCompositePart copyPart() {
        return new EnvCompositePart(getProject());
    }

    @Override
    public boolean isModified(@NotNull EnvCompositePart originalPart) {
        // Never modifiable
        return false;
    }

    @Override
    public void applySettingsTo(@NotNull EnvCompositePart userPart) {
        // Nothing to do
    }

    @Override
    public JPanel getRootPanel() {
        return rootPanel;
    }

    @Override
    public void onComponentSelected(boolean selected) {
        Color background = UIUtil.getListBackground(selected);
        rootPanel.setBackground(background);
        titleLabel.setBackground(background);
        descriptionLabel.setBackground(background);

        titleLabel.setForeground(UIUtil.getListForeground(selected));
        descriptionLabel.setForeground(UIUtil.getListForeground(selected));
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        titleLabel = new JLabel();
        titleLabel.setHorizontalAlignment(2);
        titleLabel.setHorizontalTextPosition(2);
        this.$$$loadLabelText$$$(titleLabel, ResourceBundle.getBundle("net/groboclown/idea/p4ic/P4Bundle")
                .getString("configuration.connection-choice.picker.env"));
        rootPanel.add(titleLabel, BorderLayout.NORTH);
        descriptionLabel = new JTextPane();
        descriptionLabel.setFont(UIManager.getFont("Label.font"));
        rootPanel.add(descriptionLabel, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadLabelText$$$(JLabel component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) {
                    break;
                }
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setDisplayedMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
