name: p4ic4idea-build
on: [push, pull_request]
jobs:
  build-jdk8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Plugin
        run: ./gradlew clean build

      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: p4ic4idea-plugin.jar
          path: p4ic4idea-plugin.jar
          retention-days: 5
